# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/myapp:latest', '-t', 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID', '.']
#   id: 'build-image-myapp'
#   waitFor: ['-']  # The '-' indicates that this step begins immediately.
# images:
# - 'gcr.io/$PROJECT_ID/myapp:latest'
# - 'gcr.io/$PROJECT_ID/myapp:$COMMIT_SHA'
# - 'gcr.io/$PROJECT_ID/myapp:$BUILD_ID'

name: Create Tag
on: [push]
jobs:
  Tags:
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/2.1.1',
              sha: context.sha
            })
